### PR TITLE
Rename header.js to header.js

### PR DESCRIPTION
**Pull request by Niravprajapati1**
Fix: #21

### CODE REVIEW

**Comment by nbkhope** [comment]
Hi, thanks for helping. Actually someone else was doing this issue. Please only start an issue if you are assigned to it.

I appreciate the changes in any case. Though here it seems there are unrelated changes to what the issue #21 is asking.

**Comment by nbkhope** [comment]
@Niravprajapati1 thank you, the changes look good. Looks like there are merge conflicts. Do you know how to resolve them? Let me know if you don't know.

**Comment by Niravprajapati1** [comment]
test is falling for table.js
Screenshot_2022-09-28-13-04-34-62

**Comment by Niravprajapati1** [comment]
Thanks 👍

**Pull request merged**
